sonar.organization=univers42
sonar.projectKey=Univers42_mini-baas-infra
sonar.projectName=mini-baas-infra

sonar.host.url=https://sonarcloud.io

sonar.sources=docker/services,scripts,config,docker/contracts
sonar.tests=
sonar.inclusions=**/*.js,**/*.sh,**/*.sql,**/*.yml,**/*.yaml,**/*.py

sonar.exclusions=\
  **/node_modules/**,\
  **/vendor/**,\
  **/sandbox/**,\
  **/pnpm-lock.yaml,\
  **/*.min.js,\
  **/*.min.css

sonar.javascript.file.suffixes=.js
sonar.python.file.suffixes=.py

sonar.sourceEncoding=UTF-8
