apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
      - name: auth-service
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres:5432/postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-api
spec:
  template:
    spec:
      containers:
      - name: dynamic-api
        env:
        - name: DB_DSN
          value: "postgres://postgres:postgres@postgres:5432/postgres"
        - name: MONGODB_URI
          value: "mongodb://mongo:27017"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-service
spec:
  template:
    spec:
      containers:
      - name: schema-service
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo:27017"