apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
  - ../../base

namePrefix: local-

commonLabels:
  environment: local
  tier: development

images:
  - name: mini-baas/api-gateway
    newTag: latest
  - name: mini-baas/auth-service
    newTag: latest
  - name: mini-baas/dynamic-api
    newTag: latest
  - name: mini-baas/schema-service
    newTag: latest
