// ============================================================
// Animals Seed Data — 12 real animals across all 7 zones
// ============================================================
const { ObjectId } = require('mongodb');
const now = new Date();

module.exports = [
  // ── SAVANNAH ────────────────────────────────────────────────
  {
    _id: new ObjectId('65a000000000000000000001'),
    name: 'Kibo',
    species: 'Panthera leo',
    common_name: 'African Lion',
    zone: 'savannah',
    status: 'active',
    sex: 'male',
    birth_date: new Date('2016-03-15'),
    arrival_date: new Date('2018-07-01'),
    origin_country: 'Kenya',
    weight_kg: 186.5,
    height_cm: 120,
    diet_type: 'carnivore',
    feeding_schedule: [
      { time: '08:00', food_type: 'Raw beef', quantity_kg: 6 },
      { time: '17:00', food_type: 'Raw beef + supplements', quantity_kg: 5 },
    ],
    conservation_status: 'VU',
    description:
      'Kibo is our magnificent male lion, named after the highest peak of Kilimanjaro. He arrived from the Nairobi Wildlife Conservancy as part of our international breeding program.',
    fun_facts: [
      'Kibo can roar loud enough to be heard 8km away',
      'He sleeps up to 20 hours per day',
      'His mane darkens with age — a sign of health and maturity',
    ],
    photos: ['/storage/animals/kibo_1.jpg', '/storage/animals/kibo_2.jpg'],
    cover_photo: '/storage/animals/kibo_cover.jpg',
    last_fed: now,
    total_feedings: 2847,
    assigned_keeper: 'b1000000-0000-0000-0000-000000000002',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    _id: new ObjectId('65a000000000000000000002'),
    name: 'Amara',
    species: 'Giraffa camelopardalis',
    common_name: 'Reticulated Giraffe',
    zone: 'savannah',
    status: 'active',
    sex: 'female',
    birth_date: new Date('2014-09-22'),
    arrival_date: new Date('2016-02-14'),
    origin_country: 'Tanzania',
    weight_kg: 830,
    height_cm: 520,
    diet_type: 'herbivore',
    feeding_schedule: [
      { time: '07:30', food_type: 'Acacia leaves', quantity_kg: 20 },
      { time: '12:00', food_type: 'Mixed browse', quantity_kg: 15 },
      { time: '16:30', food_type: 'Pelleted feed + hay', quantity_kg: 18 },
    ],
    conservation_status: 'VU',
    description:
      'Amara is our tallest resident at 5.2 meters. She was born at the Serengeti Research Centre and is beloved by our youngest visitors for her gentle curiosity.',
    fun_facts: [
      "Amara's tongue is 45cm long and dark purple — protecting it from sunburn",
      'She can run at 55km/h despite her height',
      'Giraffes only need 5-30 minutes of sleep per day',
    ],
    photos: ['/storage/animals/amara_1.jpg'],
    cover_photo: '/storage/animals/amara_cover.jpg',
    last_fed: now,
    total_feedings: 3961,
    assigned_keeper: 'b1000000-0000-0000-0000-000000000002',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    _id: new ObjectId('65a00000000000000000000c'),
    name: 'Zuri',
    species: 'Loxodonta africana',
    common_name: 'African Elephant',
    zone: 'savannah',
    status: 'active',
    sex: 'female',
    birth_date: new Date('2008-04-12'),
    arrival_date: new Date('2012-09-05'),
    origin_country: 'South Africa',
    weight_kg: 3200,
    height_cm: 280,
    diet_type: 'herbivore',
    feeding_schedule: [
      { time: '06:30', food_type: 'Hay and grass', quantity_kg: 50 },
      { time: '11:00', food_type: 'Fruits and vegetables', quantity_kg: 30 },
      { time: '17:00', food_type: 'Browse and bark', quantity_kg: 40 },
    ],
    conservation_status: 'VU',
    description:
      'Zuri, meaning "beautiful" in Swahili, is the gentle matriarch of our savannah. At 16 years old she leads our small herd with calm authority. She was relocated from Kruger National Park after habitat encroachment.',
    fun_facts: [
      'Zuri can recognize over 30 individual humans by scent',
      'Elephants mourn their dead and revisit bones of fallen family members',
      'She drinks up to 200 litres of water per day',
    ],
    photos: ['/storage/animals/zuri_1.jpg'],
    cover_photo: '/storage/animals/zuri_cover.jpg',
    last_fed: now,
    total_feedings: 5102,
    assigned_keeper: 'b1000000-0000-0000-0000-000000000002',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },

  // ── AQUARIUM ────────────────────────────────────────────────
  {
    _id: new ObjectId('65a000000000000000000003'),
    name: 'Nemo',
    species: 'Amphiprioninae',
    common_name: 'Clownfish',
    zone: 'aquarium',
    status: 'active',
    sex: 'male',
    birth_date: new Date('2022-01-10'),
    arrival_date: new Date('2022-04-01'),
    origin_country: 'Australia',
    weight_kg: 0.03,
    height_cm: 8,
    diet_type: 'omnivore',
    feeding_schedule: [
      { time: '09:00', food_type: 'Marine flakes', quantity_kg: 0.001 },
      { time: '15:00', food_type: 'Brine shrimp', quantity_kg: 0.001 },
    ],
    conservation_status: 'LC',
    description:
      'Found in the warm waters of our Great Barrier Reef exhibit. Nemo lives symbiotically with his sea anemone host in a stunning coral habitat.',
    fun_facts: [
      "Clownfish are immune to their anemone host's venom",
      'All clownfish are born male — the dominant one can become female',
      'They are one of the few fish species that care for their eggs',
    ],
    photos: ['/storage/animals/nemo_1.jpg'],
    cover_photo: '/storage/animals/nemo_cover.jpg',
    last_fed: now,
    total_feedings: 1203,
    assigned_keeper: 'b1000000-0000-0000-0000-000000000003',
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    _id: new ObjectId('65a000000000000000000009'),
    name: 'Marina',
    species: 'Chelonia mydas',
    common_name: 'Green Sea Turtle',
    zone: 'aquarium',
    status: 'active',
    sex: 'female',
    birth_date: new Date('2005-06-18'),
    arrival_date: new Date('2010-03-22'),
    origin_country: 'Costa Rica',
    weight_kg: 160,
    height_cm: 110,
    diet_type: 'herbivore',
    feeding_schedule: [
      { time: '08:00', food_type: 'Seagrass and lettuce', quantity_kg: 2.5 },
      { time: '14:00', food_type: 'Algae and jellyfish', quantity_kg: 2 },
    ],
    conservation_status: 'EN',
    description:
      'Marina was rescued as a hatchling off the Pacific coast of Costa Rica after a nesting beach was destroyed by coastal development. She is a star of our ocean conservation education programme.',
    fun_facts: [
      'Green sea turtles can hold their breath for up to 5 hours while sleeping',
      'Marina navigates using the Earth\'s magnetic field',
      'Sea turtles have been on Earth for over 110 million years',
    ],
    photos: ['/storage/animals/marina_1.jpg'],
    cover_photo: '/storage/animals/marina_cover.jpg',
    last_fed: now,
    total_feedings: 5730,
    assigned_keeper: 'b1000000-0000-0000-0000-000000000003',
    is_featured: false,
    created_at: now,
    updated_at: now,
  },

  // ── ARCTIC ──────────────────────────────────────────────────
  {
    _id: new ObjectId('65a000000000000000000004'),
    name: 'Glacier',
    species: 'Ursus maritimus',
    common_name: 'Polar Bear',
    zone: 'arctic',
    status: 'active',
    sex: 'female',
    birth_date: new Date('2011-12-01'),
    arrival_date: new Date('2013-06-20'),
    origin_country: 'Canada',
    weight_kg: 295,
    height_cm: 110,
    diet_type: 'carnivore',
    feeding_schedule: [
      { time: '09:00', food_type: 'Salmon + mackerel', quantity_kg: 5 },
      { time: '14:00', food_type: 'Herring + seal meat', quantity_kg: 7 },
    ],
    conservation_status: 'VU',
    description:
      'Glacier is our majestic polar bear, residing in our climate-controlled Arctic Tundra exhibit kept at -5°C. She arrived from the Toronto Wildlife Center as part of polar bear conservation efforts.',
    fun_facts: [
      'Polar bear fur is transparent, not white — it reflects light',
      'Glacier can swim continuously for 100km',
      'Her paws are slightly webbed for swimming efficiency',
    ],
    photos: ['/storage/animals/glacier_1.jpg'],
    cover_photo: '/storage/animals/glacier_cover.jpg',
    last_fed: now,
    total_feedings: 4218,
    assigned_keeper: 'b1000000-0000-0000-0000-000000000002',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    _id: new ObjectId('65a00000000000000000000a'),
    name: 'Frost',
    species: 'Aptenodytes patagonicus',
    common_name: 'King Penguin',
    zone: 'arctic',
    status: 'active',
    sex: 'male',
    birth_date: new Date('2019-07-04'),
    arrival_date: new Date('2021-01-15'),
    origin_country: 'Argentina',
    weight_kg: 14,
    height_cm: 90,
    diet_type: 'carnivore',
    feeding_schedule: [
      { time: '08:30', food_type: 'Herring', quantity_kg: 1.2 },
      { time: '14:30', food_type: 'Squid + krill', quantity_kg: 1 },
    ],
    conservation_status: 'LC',
    description:
      'Frost is the unofficial leader of our 12-strong king penguin colony. He arrived from the Patagonia Marine Research Station and is instantly recognisable by the bright orange patch behind his ear.',
    fun_facts: [
      'King penguins can dive to 300m depth',
      'Frost can hold his breath for 7 minutes underwater',
      'Penguins are monogamous — Frost has the same partner for 4 years running',
    ],
    photos: ['/storage/animals/frost_1.jpg'],
    cover_photo: '/storage/animals/frost_cover.jpg',
    last_fed: now,
    total_feedings: 1890,
    assigned_keeper: 'b1000000-0000-0000-0000-000000000003',
    is_featured: false,
    created_at: now,
    updated_at: now,
  },

  // ── RAINFOREST ──────────────────────────────────────────────
  {
    _id: new ObjectId('65a000000000000000000005'),
    name: 'Balam',
    species: 'Panthera onca',
    common_name: 'Jaguar',
    zone: 'rainforest',
    status: 'breeding',
    sex: 'male',
    birth_date: new Date('2018-08-30'),
    arrival_date: new Date('2020-11-01'),
    origin_country: 'Brazil',
    weight_kg: 95,
    height_cm: 75,
    diet_type: 'carnivore',
    feeding_schedule: [
      { time: '08:30', food_type: 'Wild boar meat', quantity_kg: 4 },
      { time: '18:00', food_type: 'Chicken with bones', quantity_kg: 3 },
    ],
    conservation_status: 'NT',
    description:
      'Balam ("jaguar" in Maya) was rescued from illegal wildlife trade in the Brazilian Amazon. He is currently in our breeding program with our female jaguar Luna.',
    fun_facts: [
      'Jaguars are the only big cats that roar AND purr',
      "Balam's bite force is the strongest of any big cat relative to size",
      'Unlike most cats, jaguars love water and are excellent swimmers',
    ],
    photos: ['/storage/animals/balam_1.jpg'],
    cover_photo: '/storage/animals/balam_cover.jpg',
    last_fed: now,
    total_feedings: 1876,
    assigned_keeper: 'b1000000-0000-0000-0000-000000000002',
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    _id: new ObjectId('65a000000000000000000008'),
    name: 'Canopy',
    species: 'Bradypus variegatus',
    common_name: 'Brown-throated Sloth',
    zone: 'rainforest',
    status: 'active',
    sex: 'female',
    birth_date: new Date('2020-02-14'),
    arrival_date: new Date('2021-08-03'),
    origin_country: 'Colombia',
    weight_kg: 4.5,
    height_cm: 58,
    diet_type: 'herbivore',
    feeding_schedule: [
      { time: '10:00', food_type: 'Cecropia leaves', quantity_kg: 0.3 },
      { time: '16:00', food_type: 'Hibiscus flowers', quantity_kg: 0.2 },
    ],
    conservation_status: 'LC',
    description:
      'Canopy is our beloved sloth, famous for spending exactly 15 hours per day sleeping. She can be found hanging from the upper canopy of the Rainforest Dome, occasionally descending for her twice-daily meal.',
    fun_facts: [
      'Sloths only descend to the ground once a week — to defecate',
      'Canopy can rotate her head 270° thanks to extra neck vertebrae',
      'Algae grows on her fur, providing natural camouflage',
    ],
    photos: ['/storage/animals/canopy_1.jpg'],
    cover_photo: '/storage/animals/canopy_cover.jpg',
    last_fed: now,
    total_feedings: 1462,
    assigned_keeper: 'b1000000-0000-0000-0000-000000000002',
    is_featured: false,
    created_at: now,
    updated_at: now,
  },

  // ── REPTILE ─────────────────────────────────────────────────
  {
    _id: new ObjectId('65a000000000000000000006'),
    name: 'Sobek',
    species: 'Crocodylus niloticus',
    common_name: 'Nile Crocodile',
    zone: 'reptile',
    status: 'active',
    sex: 'male',
    birth_date: new Date('2000-01-20'),
    arrival_date: new Date('2005-04-12'),
    origin_country: 'Egypt',
    weight_kg: 410,
    height_cm: 45,
    diet_type: 'carnivore',
    feeding_schedule: [
      { time: '11:00', food_type: 'Whole chicken', quantity_kg: 5 },
    ],
    conservation_status: 'LC',
    description:
      'Named after the ancient Egyptian crocodile god, Sobek is our oldest reptile resident at 26 years old. At 4.2 metres long, he commands the entire Nile River habitat exhibit.',
    fun_facts: [
      'Nile crocodiles can live to be 100 years old',
      'Sobek can go months without eating after a large meal',
      'Crocodiles have the strongest bite force of any living animal — 3,700 PSI',
    ],
    photos: ['/storage/animals/sobek_1.jpg'],
    cover_photo: '/storage/animals/sobek_cover.jpg',
    last_fed: now,
    total_feedings: 3150,
    assigned_keeper: 'b1000000-0000-0000-0000-000000000003',
    is_featured: false,
    created_at: now,
    updated_at: now,
  },

  // ── AVIARY ──────────────────────────────────────────────────
  {
    _id: new ObjectId('65a000000000000000000007'),
    name: 'Phoenix',
    species: 'Phoenicopterus roseus',
    common_name: 'Greater Flamingo',
    zone: 'aviary',
    status: 'active',
    sex: 'female',
    birth_date: new Date('2017-11-05'),
    arrival_date: new Date('2019-03-20'),
    origin_country: 'France',
    weight_kg: 3.5,
    height_cm: 140,
    diet_type: 'omnivore',
    feeding_schedule: [
      { time: '07:30', food_type: 'Brine shrimp + algae pellets', quantity_kg: 0.5 },
      { time: '15:00', food_type: 'Spirulina mix', quantity_kg: 0.3 },
    ],
    conservation_status: 'LC',
    description:
      'Phoenix is the lead bird in our flock of 28 greater flamingos. Her vivid pink plumage comes from the carotenoid pigments in her shrimp-heavy diet — flamingos in the wild that eat fewer shrimp appear white.',
    fun_facts: [
      'Flamingos can only eat with their heads upside-down',
      'Phoenix sleeps standing on one leg — scientists still debate why',
      'Flamingo flocks can number in the hundreds of thousands in the wild',
    ],
    photos: ['/storage/animals/phoenix_1.jpg'],
    cover_photo: '/storage/animals/phoenix_cover.jpg',
    last_fed: now,
    total_feedings: 2580,
    assigned_keeper: 'b1000000-0000-0000-0000-000000000003',
    is_featured: false,
    created_at: now,
    updated_at: now,
  },

  // ── PETTING ─────────────────────────────────────────────────
  {
    _id: new ObjectId('65a00000000000000000000b'),
    name: 'Clover',
    species: 'Oryctolagus cuniculus',
    common_name: 'Holland Lop Rabbit',
    zone: 'petting',
    status: 'active',
    sex: 'female',
    birth_date: new Date('2023-03-01'),
    arrival_date: new Date('2023-05-15'),
    origin_country: 'Netherlands',
    weight_kg: 1.8,
    height_cm: 25,
    diet_type: 'herbivore',
    feeding_schedule: [
      { time: '08:00', food_type: 'Timothy hay', quantity_kg: 0.15 },
      { time: '12:00', food_type: 'Fresh greens', quantity_kg: 0.1 },
      { time: '17:00', food_type: 'Pellets + carrot', quantity_kg: 0.08 },
    ],
    conservation_status: 'LC',
    description:
      'Clover is the star of our Petting Zone — a fluffy holland lop with floppy ears and a calm temperament that makes her perfect for young visitors to interact with. She loves being petted behind her ears.',
    fun_facts: [
      'Rabbits can see nearly 360° without moving their head',
      "Clover 'binkies' (jumps and twists mid-air) when she's happy",
      'A rabbit\'s teeth never stop growing — she chew on hay to keep them trimmed',
    ],
    photos: ['/storage/animals/clover_1.jpg'],
    cover_photo: '/storage/animals/clover_cover.jpg',
    last_fed: now,
    total_feedings: 920,
    assigned_keeper: 'b1000000-0000-0000-0000-000000000002',
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
];
