# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dlesieur <dlesieur@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/04/09 23:34:46 by dlesieur          #+#    #+#              #
#    Updated: 2026/04/09 23:34:47 by dlesieur         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# syntax=docker/dockerfile:1
# File: docker/services/minio/Dockerfile

FROM minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
EXPOSE 9000 9001
