#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-.env}"
FORCE="${FORCE:-0}"

if [[ -f "$ENV_FILE" && "$FORCE" != "1" ]]; then
  echo "Error: $ENV_FILE already exists. Use FORCE=1 to overwrite." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "Error: openssl is required but not installed." >&2
  exit 1
fi

b64url() {
  openssl base64 -A | tr '+/' '-_' | tr -d '='
  return 0
}

gen_alnum() {
  local length="$1"
  local out=""
  while [[ "${#out}" -lt "$length" ]]; do
    out+="$(openssl rand -base64 48 | tr -dc 'A-Za-z0-9')"
  done
  printf '%s' "${out:0:length}"
  return 0
}

jwt_hs256() {
  local secret="$1"
  local role="$2"
  local iat exp header payload sig

  iat="$(date +%s)"
  exp="$((iat + 157680000))" # 5 years

  header='{"alg":"HS256","typ":"JWT"}'
  payload=$(printf '{"role":"%s","iss":"supabase","iat":%s,"exp":%s}' "$role" "$iat" "$exp")

  local h p
  h="$(printf '%s' "$header" | b64url)"
  p="$(printf '%s' "$payload" | b64url)"
  sig="$(printf '%s' "$h.$p" | openssl dgst -sha256 -hmac "$secret" -binary | b64url)"

  printf '%s.%s.%s' "$h" "$p" "$sig"
  return 0
}

POSTGRES_USER="postgres"
POSTGRES_PASSWORD="$(gen_alnum 24)"
POSTGRES_DB="postgres"

JWT_SECRET="$(openssl rand -hex 32)"
VAULT_ENC_KEY="$(openssl rand -hex 16)"
MINIO_ROOT_PASSWORD="$(openssl rand -hex 16)"

ANON_KEY="$(jwt_hs256 "$JWT_SECRET" "anon")"
SERVICE_ROLE_KEY="$(jwt_hs256 "$JWT_SECRET" "service_role")"

DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
PGRST_DB_URI="${DATABASE_URL}"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/generate-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# For local self-hosting only. Do not commit this file.

# Core database connection used by multiple services
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
DATABASE_URL=${DATABASE_URL}
PGRST_DB_URI=${PGRST_DB_URI}

# Kong key-auth and CORS policy
KONG_PUBLIC_API_KEY=public-anon-key
KONG_SERVICE_API_KEY=service-role-key
KONG_CORS_ORIGIN_APP=http://localhost:3000
KONG_CORS_ORIGIN_PLAYGROUND=http://localhost:3100
KONG_CORS_ORIGIN_STUDIO=http://localhost:3001

# GoTrue
API_EXTERNAL_URL=http://localhost:8000/auth/v1
GOTRUE_SITE_URL=http://localhost:3001
JWT_SECRET=${JWT_SECRET}

# PostgREST
PGRST_DB_SCHEMA=public
PGRST_DB_ANON_ROLE=postgres

# Realtime (dlesieur/realtime-agnostic)
REALTIME_PORT=4002
RUST_LOG=info

# Supabase API keys (legacy HS256 JWTs)
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# MinIO
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# Supavisor
VAULT_ENC_KEY=${VAULT_ENC_KEY}

# Studio
STUDIO_PG_META_URL=http://host.docker.internal:8080
SUPABASE_URL=http://localhost:8000
SUPABASE_PUBLIC_URL=http://localhost:8000

# MongoDB
MONGO_URI=mongodb://mongo:27017
MONGO_DB_NAME=mini_baas

# Adapter Registry
ADAPTER_REGISTRY_DATABASE_URL=${DATABASE_URL}
ADAPTER_REGISTRY_URL=http://adapter-registry:3020

# Query Router
QUERY_ROUTER_URL=http://query-router:4001

# Logging
LOG_LEVEL=info
EOF

chmod 600 "$ENV_FILE"
echo "Generated $ENV_FILE"
