# File: k8s/overlays/dev/values-postgresql.yaml
# Dev overrides for bitnami/postgresql
auth:
  postgresPassword: "postgres"

primary:
  persistence:
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

metrics:
  enabled: false
