[postgres]
POSTGRES_USER = postgres
POSTGRES_DB = postgres
POSTGRES_HOST = postgres
POSTGRES_PORT = 5432
POSTGRES_SSLMODE = disable
DEFAULT_DATABASE_ENGINE = postgres
SCHEMA_FILE = ../../../models/user.sql
SEED_FILE = ../../../models/seeds.sql
PROJECT_INIT_MARKER = track_binocle_20260503
