[services]
postgres = true
supavisor = true
postgrest = true
pg-meta = true
kong = true
redis = true

gotrue = false
storage = false
realtime = false
studio = false
minio = false
mongo = false
trino = false
waf = false
vault = false
observability = false
