-- ============================================================
-- 001_initial_schema.sql — Core relational tables for zoo_app
-- ============================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── Staff ─────────────────────────────────────────────────────
CREATE TABLE staff (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email       TEXT UNIQUE NOT NULL,
    full_name   TEXT NOT NULL,
    role        TEXT NOT NULL CHECK (role IN ('admin', 'zookeeper', 'vet', 'reception')),
    zone        TEXT CHECK (zone IN ('savannah', 'arctic', 'rainforest', 'aquarium', 'reptile', 'aviary', 'petting')),
    avatar_url  TEXT,
    phone       TEXT,
    hired_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Ticket Types ──────────────────────────────────────────────
CREATE TABLE ticket_types (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        TEXT UNIQUE NOT NULL,
    price_eur   NUMERIC(8,2) NOT NULL CHECK (price_eur >= 0),
    description TEXT,
    color       TEXT,               -- hex badge colour for UI
    max_per_day INTEGER DEFAULT 500,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Tickets (individual purchases) ────────────────────────────
CREATE TABLE tickets (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ticket_type_id  UUID NOT NULL REFERENCES ticket_types(id),
    visitor_name    TEXT NOT NULL,
    visitor_email   TEXT,
    visit_date      DATE NOT NULL,
    quantity         INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    total_eur       NUMERIC(10,2) NOT NULL,
    qr_code         TEXT,           -- generated by trigger
    status          TEXT NOT NULL DEFAULT 'valid'
                        CHECK (status IN ('valid', 'used', 'cancelled', 'refunded')),
    sold_by         UUID REFERENCES staff(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_tickets_visit_date ON tickets (visit_date);
CREATE INDEX idx_tickets_status     ON tickets (status);
CREATE INDEX idx_tickets_type       ON tickets (ticket_type_id);

-- ── Health Records (links to Mongo animal _id via text) ───────
CREATE TABLE health_records (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    animal_id       TEXT NOT NULL,           -- Mongo ObjectId as string
    vet_id          UUID NOT NULL REFERENCES staff(id),
    record_type     TEXT NOT NULL CHECK (record_type IN (
                        'checkup', 'vaccination', 'surgery', 'dental',
                        'blood_work', 'injury', 'observation')),
    diagnosis       TEXT,
    treatment       TEXT,
    medications     JSONB DEFAULT '[]'::jsonb,
    weight_kg       NUMERIC(10,2),
    temperature_c   NUMERIC(4,1),
    next_checkup    DATE,
    notes           TEXT,
    attachments     JSONB DEFAULT '[]'::jsonb,  -- file paths
    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_health_animal   ON health_records (animal_id, recorded_at DESC);
CREATE INDEX idx_health_vet      ON health_records (vet_id);
CREATE INDEX idx_health_type     ON health_records (record_type);

-- ── Staff Schedules ───────────────────────────────────────────
CREATE TABLE staff_schedules (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    staff_id    UUID NOT NULL REFERENCES staff(id),
    shift_date  DATE NOT NULL,
    start_time  TIME NOT NULL,
    end_time    TIME NOT NULL,
    zone        TEXT CHECK (zone IN ('savannah', 'arctic', 'rainforest', 'aquarium', 'reptile', 'aviary', 'petting')),
    notes       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (staff_id, shift_date, start_time)
);

CREATE INDEX idx_schedule_date ON staff_schedules (shift_date);

-- ── Visitor Stats (daily aggregates) ──────────────────────────
CREATE TABLE visitor_stats (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    stat_date       DATE UNIQUE NOT NULL,
    total_visitors  INTEGER NOT NULL DEFAULT 0,
    total_revenue   NUMERIC(12,2) NOT NULL DEFAULT 0,
    tickets_sold    INTEGER NOT NULL DEFAULT 0,
    top_zone        TEXT,
    weather         TEXT,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Audit Log ─────────────────────────────────────────────────
CREATE TABLE audit_log (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    actor_id    UUID REFERENCES staff(id),
    action      TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id   TEXT NOT NULL,
    payload     JSONB DEFAULT '{}'::jsonb,
    ip_address  INET,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_actor  ON audit_log (actor_id, created_at DESC);
CREATE INDEX idx_audit_entity ON audit_log (entity_type, entity_id);
